services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./vector_data:/chroma/.chroma/index
    command: chroma run --path /chroma/.chroma/index --host 0.0.0.0 --port 8000
